on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Automatically update the contributors list in the README
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@83ea0b4f1ac928fbfe88b9e8460a932a528eb79f #v2.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
