on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Automatically update the contributors list in the README
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@1ff4c56187458b34cd602aee93e897344ce34bfc #v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
