# Installs Rust and checks formatting + linting

name: Lint Rust

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"
      - "pnpm-lock.yaml"
      - "README.md"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Disable git core.autocrlf on Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up pnpm package manager
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Install nodecar dependencies
        working-directory: ./nodecar
        run: |
          echo "DEBUG: Installing nodecar dependencies..."
          pnpm install --frozen-lockfile
          echo "DEBUG: Current directory: $(pwd)"
          echo "DEBUG: Contents of nodecar directory:"
          ls -la
          echo "DEBUG: Checking if package.json exists:"
          cat package.json | head -20
          echo "DEBUG: Checking pnpm version and cache:"
          pnpm --version
          echo "DEBUG: Running pnpm install..."
          pnpm install --frozen-lockfile
          echo "DEBUG: After pnpm install - checking node_modules:"
          ls -la node_modules/ | head -20
          echo "DEBUG: Checking if specific dependencies exist:"
          ls -la node_modules/commander || echo "commander not found"
          ls -la node_modules/get-port || echo "get-port not found"
          ls -la node_modules/proxy-chain || echo "proxy-chain not found"
          echo "DEBUG: Checking get-port package.json type:"
          cat node_modules/get-port/package.json | grep -E '"type":|"main":|"module":|"exports":' || echo "No ESM info found"
          echo "DEBUG: Checking what TypeScript can resolve:"
          npx tsc --noEmit --listFiles | head -20 || echo "TypeScript check failed"

      - name: Build nodecar binary
        shell: bash
        working-directory: ./nodecar
        run: |
          echo "DEBUG: Building nodecar binary..."
          echo "DEBUG: Current directory: $(pwd)"
          echo "DEBUG: Contents of nodecar directory:"
          ls -la
          echo "DEBUG: Checking if node_modules still exists:"
          ls -la node_modules/ | head -10 || echo "node_modules not found!"
          echo "DEBUG: Checking TypeScript config:"
          cat tsconfig.json
          echo "DEBUG: Checking src directory:"
          ls -la src/
          echo "DEBUG: Testing individual imports:"
          echo "import { program } from 'commander';" > test-import.ts
          npx tsc --noEmit test-import.ts || echo "Commander import failed"
          echo "import getPort from 'get-port';" > test-import.ts  
          npx tsc --noEmit test-import.ts || echo "get-port import failed"
          echo "import * as ProxyChain from 'proxy-chain';" > test-import.ts
          npx tsc --noEmit test-import.ts || echo "proxy-chain import failed"
          rm test-import.ts
          echo "DEBUG: Running build script based on OS..."
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "DEBUG: Running Linux x64 build..."
            pnpm run build:linux-x64
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "DEBUG: Running macOS aarch64 build..."
            pnpm run build:aarch64
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "DEBUG: Running Windows x64 build..."
            pnpm run build:win-x64
          fi

      - name: Copy nodecar binary to Tauri binaries
        run: |
          mkdir -p src-tauri/binaries
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cp nodecar/dist/nodecar src-tauri/binaries/nodecar-x86_64-unknown-linux-gnu
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp nodecar/dist/nodecar src-tauri/binaries/nodecar-aarch64-apple-darwin
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp nodecar/dist/nodecar.exe src-tauri/binaries/nodecar-x86_64-pc-windows-msvc.exe
          fi

      - name: Create empty 'dist' directory
        run: mkdir dist

      - name: Run rustfmt check
        run: cargo fmt --all -- --check
        working-directory: src-tauri

      - name: Run clippy check and deny warnings
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: src-tauri

      - name: Run Rust unit tests
        run: cargo test
        working-directory: src-tauri
