# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

# Security vulnerability scanning for Donut Browser
# Scans dependencies in package managers (npm/pnpm, Cargo) for known vulnerabilities
# Runs on schedule and when dependencies change

name: Security Vulnerability Scan

on:
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "package-lock.json"
      - "src-tauri/Cargo.toml"
      - "src-tauri/Cargo.lock"
      - "nodecar/package.json"
      - "nodecar/package-lock.json"
      - ".github/workflows/osv.yml"
  merge_group:
    branches: ["main"]
  schedule:
    # Run weekly on Tuesdays at 2:20 PM UTC
    - cron: "20 14 * * 2"
  push:
    branches: ["main"]
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "package-lock.json"
      - "src-tauri/Cargo.toml"
      - "src-tauri/Cargo.lock"
      - "nodecar/package.json"
      - "nodecar/package-lock.json"

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read

jobs:
  scan-scheduled:
    name: Scheduled Security Scan
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78" # v1.7.1
    with:
      scan-args: |-
        -r
        --skip-git
        --lockfile=package-lock.json
        --lockfile=pnpm-lock.yaml
        --lockfile=src-tauri/Cargo.lock
        --lockfile=nodecar/package-lock.json
        ./

  scan-pr:
    name: PR Security Scan
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78" # v1.7.1
    with:
      scan-args: |-
        -r
        --skip-git
        --lockfile=package-lock.json
        --lockfile=pnpm-lock.yaml
        --lockfile=src-tauri/Cargo.lock
        --lockfile=nodecar/package-lock.json
        ./
